version: '3'
services:
  api:
    build: api/
    command: 'npm run start:dev'
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules
    ports: 
      - "3000:3000"
    environment:
      HTTP_PORT: 3000
